import { vi } from "vitest";
import type { FullResumeDTO } from "@/shared/types/resume-builder";

export function createMockResume(
  overrides?: Partial<FullResumeDTO>,
): FullResumeDTO {
  return {
    id: "resume-1",
    title: "My Resume",
    template_id: "00000000-0000-0000-0000-000000000001",
    font_family: "Georgia",
    primary_color: "#2563eb",
    text_color: "#111827",
    spacing: 100,
    margin_top: 40,
    margin_bottom: 40,
    margin_left: 40,
    margin_right: 40,
    layout_mode: "single",
    sidebar_width: 35,
    font_size: 12,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    contact: {
      full_name: "John Doe",
      email: "john@example.com",
      phone: "+1234567890",
      location: "New York, NY",
      website: "https://johndoe.com",
      linkedin: "linkedin.com/in/johndoe",
      github: "github.com/johndoe",
    },
    summary: { content: "Experienced software engineer" },
    experiences: [],
    educations: [],
    skills: [],
    languages: [],
    certifications: [],
    projects: [],
    volunteering: [],
    custom_sections: [],
    section_order: [],
    ...overrides,
  };
}

export function createMockStoreState(resumeOverrides?: Partial<FullResumeDTO>) {
  const resume = createMockResume(resumeOverrides);
  return {
    resume,
    activeSection: "contact" as const,
    saveStatus: "idle" as const,
    isDirty: false,
    setResume: vi.fn(),
    setActiveSection: vi.fn(),
    setSaveStatus: vi.fn(),
    markDirty: vi.fn(),
    markClean: vi.fn(),
    updateContact: vi.fn(),
    updateSummary: vi.fn(),
    updateDesign: vi.fn(),
    setExperiences: vi.fn(),
    setEducations: vi.fn(),
    setSkills: vi.fn(),
    setLanguages: vi.fn(),
    setCertifications: vi.fn(),
    setProjects: vi.fn(),
    setVolunteering: vi.fn(),
    setCustomSections: vi.fn(),
    setSectionOrder: vi.fn(),
    addExperience: vi.fn(),
    updateExperience: vi.fn(),
    removeExperience: vi.fn(),
    addEducation: vi.fn(),
    updateEducation: vi.fn(),
    removeEducation: vi.fn(),
    addSkill: vi.fn(),
    updateSkill: vi.fn(),
    removeSkill: vi.fn(),
    addLanguage: vi.fn(),
    updateLanguage: vi.fn(),
    removeLanguage: vi.fn(),
    addCertification: vi.fn(),
    updateCertification: vi.fn(),
    removeCertification: vi.fn(),
    addProject: vi.fn(),
    updateProject: vi.fn(),
    removeProject: vi.fn(),
    addVolunteering: vi.fn(),
    updateVolunteering: vi.fn(),
    removeVolunteering: vi.fn(),
    addCustomSection: vi.fn(),
    updateCustomSection: vi.fn(),
    removeCustomSection: vi.fn(),
  };
}
