import type { LayoutMode } from "@/shared/types/resume-builder";

interface LayoutPresetThumbnailProps {
  readonly mode: LayoutMode;
  readonly isActive: boolean;
  readonly onClick: () => void;
  readonly label: string;
}

export function LayoutPresetThumbnail({
  mode,
  isActive,
  onClick,
  label,
}: LayoutPresetThumbnailProps) {
  return (
    <button
      type="button"
      onClick={onClick}
      className={`flex flex-col items-center gap-1.5 rounded-lg border-2 p-2 transition-colors ${
        isActive
          ? "border-primary bg-primary/5"
          : "border-border hover:border-border/80"
      }`}
    >
      <svg
        viewBox="0 0 40 52"
        className="h-12 w-9"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
      >
        <rect
          x="0.5"
          y="0.5"
          width="39"
          height="51"
          rx="1.5"
          stroke="currentColor"
          strokeWidth="1"
          className="text-gray-300"
        />
        {mode === "single" && (
          <>
            <rect
              x="6"
              y="5"
              width="28"
              height="3"
              rx="1"
              className="fill-gray-300"
            />
            <rect
              x="6"
              y="11"
              width="28"
              height="2"
              rx="0.5"
              className="fill-gray-200"
            />
            <rect
              x="6"
              y="15"
              width="28"
              height="2"
              rx="0.5"
              className="fill-gray-200"
            />
            <rect
              x="6"
              y="19"
              width="20"
              height="2"
              rx="0.5"
              className="fill-gray-200"
            />
            <rect
              x="6"
              y="25"
              width="28"
              height="3"
              rx="1"
              className="fill-gray-300"
            />
            <rect
              x="6"
              y="31"
              width="28"
              height="2"
              rx="0.5"
              className="fill-gray-200"
            />
            <rect
              x="6"
              y="35"
              width="28"
              height="2"
              rx="0.5"
              className="fill-gray-200"
            />
            <rect
              x="6"
              y="41"
              width="28"
              height="3"
              rx="1"
              className="fill-gray-300"
            />
            <rect
              x="6"
              y="46"
              width="20"
              height="2"
              rx="0.5"
              className="fill-gray-200"
            />
          </>
        )}
        {mode === "double-left" && (
          <>
            <rect
              x="2"
              y="2"
              width="13"
              height="48"
              rx="1"
              className="fill-gray-100"
            />
            <rect
              x="4"
              y="5"
              width="9"
              height="2"
              rx="0.5"
              className="fill-gray-300"
            />
            <rect
              x="4"
              y="9"
              width="9"
              height="1.5"
              rx="0.5"
              className="fill-gray-200"
            />
            <rect
              x="4"
              y="12"
              width="9"
              height="1.5"
              rx="0.5"
              className="fill-gray-200"
            />
            <rect
              x="4"
              y="17"
              width="9"
              height="2"
              rx="0.5"
              className="fill-gray-300"
            />
            <rect
              x="4"
              y="21"
              width="9"
              height="1.5"
              rx="0.5"
              className="fill-gray-200"
            />
            <rect
              x="4"
              y="24"
              width="9"
              height="1.5"
              rx="0.5"
              className="fill-gray-200"
            />
            <rect
              x="17"
              y="5"
              width="20"
              height="3"
              rx="1"
              className="fill-gray-300"
            />
            <rect
              x="17"
              y="11"
              width="20"
              height="2"
              rx="0.5"
              className="fill-gray-200"
            />
            <rect
              x="17"
              y="15"
              width="20"
              height="2"
              rx="0.5"
              className="fill-gray-200"
            />
            <rect
              x="17"
              y="19"
              width="14"
              height="2"
              rx="0.5"
              className="fill-gray-200"
            />
            <rect
              x="17"
              y="25"
              width="20"
              height="3"
              rx="1"
              className="fill-gray-300"
            />
            <rect
              x="17"
              y="31"
              width="20"
              height="2"
              rx="0.5"
              className="fill-gray-200"
            />
            <rect
              x="17"
              y="35"
              width="20"
              height="2"
              rx="0.5"
              className="fill-gray-200"
            />
          </>
        )}
        {mode === "double-right" && (
          <>
            <rect
              x="25"
              y="2"
              width="13"
              height="48"
              rx="1"
              className="fill-gray-100"
            />
            <rect
              x="27"
              y="5"
              width="9"
              height="2"
              rx="0.5"
              className="fill-gray-300"
            />
            <rect
              x="27"
              y="9"
              width="9"
              height="1.5"
              rx="0.5"
              className="fill-gray-200"
            />
            <rect
              x="27"
              y="12"
              width="9"
              height="1.5"
              rx="0.5"
              className="fill-gray-200"
            />
            <rect
              x="27"
              y="17"
              width="9"
              height="2"
              rx="0.5"
              className="fill-gray-300"
            />
            <rect
              x="27"
              y="21"
              width="9"
              height="1.5"
              rx="0.5"
              className="fill-gray-200"
            />
            <rect
              x="27"
              y="24"
              width="9"
              height="1.5"
              rx="0.5"
              className="fill-gray-200"
            />
            <rect
              x="3"
              y="5"
              width="20"
              height="3"
              rx="1"
              className="fill-gray-300"
            />
            <rect
              x="3"
              y="11"
              width="20"
              height="2"
              rx="0.5"
              className="fill-gray-200"
            />
            <rect
              x="3"
              y="15"
              width="20"
              height="2"
              rx="0.5"
              className="fill-gray-200"
            />
            <rect
              x="3"
              y="19"
              width="14"
              height="2"
              rx="0.5"
              className="fill-gray-200"
            />
            <rect
              x="3"
              y="25"
              width="20"
              height="3"
              rx="1"
              className="fill-gray-300"
            />
            <rect
              x="3"
              y="31"
              width="20"
              height="2"
              rx="0.5"
              className="fill-gray-200"
            />
            <rect
              x="3"
              y="35"
              width="20"
              height="2"
              rx="0.5"
              className="fill-gray-200"
            />
          </>
        )}
        {mode === "custom" && (
          <>
            <rect
              x="2"
              y="2"
              width="13"
              height="48"
              rx="1"
              className="fill-gray-100"
              strokeDasharray="2 2"
              stroke="currentColor"
              strokeWidth="0.5"
            />
            <rect
              x="4"
              y="5"
              width="9"
              height="2"
              rx="0.5"
              className="fill-gray-300"
            />
            <rect
              x="4"
              y="9"
              width="9"
              height="1.5"
              rx="0.5"
              className="fill-gray-200"
            />
            <rect
              x="17"
              y="5"
              width="20"
              height="3"
              rx="1"
              className="fill-gray-300"
            />
            <rect
              x="17"
              y="11"
              width="20"
              height="2"
              rx="0.5"
              className="fill-gray-200"
            />
            <rect
              x="17"
              y="15"
              width="20"
              height="2"
              rx="0.5"
              className="fill-gray-200"
            />
            <rect
              x="17"
              y="25"
              width="20"
              height="3"
              rx="1"
              className="fill-gray-300"
            />
            <rect
              x="17"
              y="31"
              width="20"
              height="2"
              rx="0.5"
              className="fill-gray-200"
            />
            <text
              x="10"
              y="36"
              textAnchor="middle"
              fontSize="8"
              className="fill-gray-400"
            >
              ?
            </text>
          </>
        )}
      </svg>
      <span className="text-[10px] font-medium text-muted-foreground">
        {label}
      </span>
    </button>
  );
}
